apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Replace with your email address so you can be notified of expiring certificates
    email: <Your email>
    # Use Let's Encrypt staging for testing as production enforces stricter usage limits
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # The secret that holds the generated private key used to communicate with Let's Encrypt
      name: letsencrypt-staging-account-key
    dns01:
      providers:
      # The name given to this CloudDNS provider, multiple CloudDNS providers can be added with different names
      - name: gcp-clouddns-provider
        clouddns:
          # The ID of the GCP project
          project: <Your GCP project>
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: gcp-dns-sa-key.json
